baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

params:
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Thomas Ferreira de Lima"
    subtitle: "Researcher @ NEC Labs America."
    content: "My research is on Integrated Neuromorphic Photonics, which involves building large-scale photonic circuits on chip that emulate the functionality of neural networks, but working at GHz speed."
    image: /images/headshot.jpg
    button:
      enable: true
      name: "C.V."
      url: "cv/"
      download: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/thomaslima
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ferreiradelima/
        - icon: fa fa-envelope
          url: mailto:website@tlima.me
        - icon: fa fa-graduation-cap
          url: https://scholar.google.com/citations?hl=en&user=462r5jQAAAAJ
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      In 2021, I completed my Ph.D. in [Paul Prucnal's lab](http://faculty.ee.princeton.edu/prucnal/) at Princeton University. My research is on <i>Integrated Neuromorphic Photonics</i>, which involves building large-scale photonic circuits on chip that emulate the functionality of neural networks, but working at GHz speed. See my [online CV](cv/) for more detail.
      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"
