baseURL: "https://tlima.me"
languageCode: "en-us"
title: "Thomas Ferreira de Lima | Personal Page"
theme: hugo-profile
contentDir: content
googleAnalytics: G-9JBSB4773F

params:
  title: "Thomas Ferreira de Lima"
  description: Personal Website
  favicon: "/images/fav.png"

  # Whether the fade animations on the home page will be enabled
  animate: true

  useBootstrapCDN: true

  font:
    fontSize: 1.0rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
    primaryColor: "#0061c9"
  #   secondaryColor:
    highlightColor: "#c9e8ff"

    darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
      primaryColor: "#c9e8ff"
      secondaryColor: "#ffffff"
      highlightColor: "#23577e"

  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Thomas Ferreira de Lima"
    subtitle: "Welcome to my personal website."
    content: "I am an academic researcher in Electrical Engineering. My research is on Integrated Photonics for Computing, which involves using the physics of optical lightwaves to emulate the functionality of neural networks, but working at GHz speed."
    image: /images/IMG_7922_cropped.jpg
    button:
      enable: true
      name: "C.V."
      url: "cv/"
      download: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/thomaslima
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ferreiradelima/
        - icon: fa fa-envelope
          url: mailto:website@tlima.me
        - icon: fa fa-graduation-cap
          url: https://scholar.google.com/citations?hl=en&user=462r5jQAAAAJ
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  about:
    enable: true
    title: "About Me"
    image: "/images/IMG_7752_cropped.jpeg"
    content: |-
      I come from Brazil but live in Princeton, NJ, USA, and currently work as a researcher at NEC Labs America.
      As a member of the IEEE Photonics Society and the Optica Society, I am constantly exploring new research avenues and contribute to advancing knowledge in my field.
      Outside of work, I enjoy swimming, hiking and landscape photography ([flickr page](https://www.flickr.com/people/197302687@N07/)). With my fujifilm camera, I seek to capture the beauty of light in nature while traveling or hiking.
      See my [online CV](cv/) for more professional details.
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  #Contact
  contact:
    enable: true
    title: "Ways to Contact Me"
    content: My inbox is occasionally monitored. Check the social links above for contacting me via linkedin or github. If those don't work, try the following email address. I’ll try my best to get back to you!
    email: website@tlima.me
    btnName: website@tlima.me
  footer:
    recentPosts: false